const data = [
  {
    stjCd: "AP003",
    lgnm: "MS CORPORATION",
    stj: "BCP KODIKONDA",
    dty: "Regular",
    cxdt: "",
    gstin: "05ABNTY3290P8ZA",
    einvoiceStatus: "Yes",
    nba: [
      "Bonded Warehouse",
      "EOU / STP / EHTP",
      "Factory / Manufacturing",
      "Input Service Distributor (ISD)",
      "Leasing Business",
    ],
    lstupdt: "05/01/2017",
    rgdt: "05/05/2017",
    ctb: "Foreign LLP",
    sts: "Provisional",
    ctjCd: "AP004",
    ctj: "BCP THUMMAKUNTA",
    tradeNam: "ALTON PLASTIC PRIVATE LTD",
    adadr: [
      {
        addr: {
          bnm: "ELPHINSTONE BUILDING",
          st: "10, VEER NARIMAN ROAD",
          loc: "FORT",
          bno: "10",
          stcd: "Rajasthan",
          flno: "1ST FLOOR",
          lt: "74.2179",
          lg: "27.0238",
          pncd: "400001",
        },
        ntr: ["Wholesale Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "KATGARA HOUSE",
        st: "15, L JAGMOHANDAS MARG",
        loc: "MALABAR HILL",
        bno: "5",
        stcd: "Maharashtra",
        flno: "4TH FLOOR",
        lt: "74.2179",
        lg: "27.0238",
        pncd: "400006",
      },
      ntr: ["Wholesale Business"],
    },
  },
  {
    stjCd: "AP067",
    lgnm: "GreenVista Landscapes",
    stj: "Transforming Outdoor Spaces",
    dty: "Regular",
    cxdt: "",
    gstin: "56PQRST7890UVWX",
    einvoiceStatus: "Yes",
    nba: ["Landscaping Services"],
    lstupdt: "06/10/2023",
    rgdt: "11/22/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP068",
    ctj: "Landscape Designer",
    tradeNam: "EcoScapes",
    adadr: [
      {
        addr: {
          bnm: "Eco Landscapes",
          st: "30, Green Street",
          loc: "Greenery District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10045",
        },
        ntr: ["Landscaping Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Nature Hub",
        st: "15, Landscape Avenue",
        loc: "Natureville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10046",
      },
      ntr: ["Landscaping Business"],
    },
  },
  {
    stjCd: "AP068",
    lgnm: "InnoHealth Labs",
    stj: "Innovating Healthcare",
    dty: "Regular",
    cxdt: "",
    gstin: "12YZAB5678CDEFG",
    einvoiceStatus: "Yes",
    nba: ["Healthcare Services"],
    lstupdt: "05/15/2023",
    rgdt: "10/28/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP069",
    ctj: "Medical Researcher",
    tradeNam: "HealthInnovate",
    adadr: [
      {
        addr: {
          bnm: "Health Innovate Center",
          st: "20, Health Street",
          loc: "Health District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90043",
        },
        ntr: ["Healthcare Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Medical Hub",
        st: "25, Medical Avenue",
        loc: "Medicineville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90044",
      },
      ntr: ["Healthcare Business"],
    },
  },
  {
    stjCd: "AP065",
    lgnm: "GourmetDelights",
    stj: "Delicious Culinary Creations",
    dty: "Regular",
    cxdt: "",
    gstin: "12YZAB9078CDEFG",
    einvoiceStatus: "Yes",
    nba: ["Food and Beverage"],
    lstupdt: "08/12/2023",
    rgdt: "01/20/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP066",
    ctj: "Chef",
    tradeNam: "TasteFusion",
    adadr: [
      {
        addr: {
          bnm: "Culinary Delights",
          st: "30, Gourmet Street",
          loc: "Culinary District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10045",
        },
        ntr: ["Food and Beverage Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Flavor Hub",
        st: "15, Gourmet Avenue",
        loc: "Flavorville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10046",
      },
      ntr: ["Food and Beverage Business"],
    },
  },
  {
    stjCd: "AP066",
    lgnm: "InnoFitness",
    stj: "Innovate Your Fitness",
    dty: "Regular",
    cxdt: "",
    gstin: "90HIJK1234LMNOP",
    einvoiceStatus: "Yes",
    nba: ["Fitness and Wellness"],
    lstupdt: "07/15/2023",
    rgdt: "12/05/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP067",
    ctj: "Fitness Trainer",
    tradeNam: "FitInnovate",
    adadr: [
      {
        addr: {
          bnm: "Fitness Center",
          st: "20, Fitness Street",
          loc: "Wellness District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90043",
        },
        ntr: ["Fitness and Wellness Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Wellness Hub",
        st: "25, Wellness Avenue",
        loc: "Healthville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90044",
      },
      ntr: ["Fitness and Wellness Business"],
    },
  },
  {
    stjCd: "AP063",
    lgnm: "GreenTech Innovations",
    stj: "Pioneering Sustainable Tech",
    dty: "Regular",
    cxdt: "",
    gstin: "90HIJK3334LMNOP",
    einvoiceStatus: "Yes",
    nba: ["Technology Services"],
    lstupdt: "10/18/2023",
    rgdt: "03/22/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP064",
    ctj: "Tech Pioneer",
    tradeNam: "EcoTech",
    adadr: [
      {
        addr: {
          bnm: "Eco Innovate Center",
          st: "30, Green Street",
          loc: "Eco District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10043",
        },
        ntr: ["Technology Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Eco Hub",
        st: "15, Innovation Avenue",
        loc: "Innovationville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10044",
      },
      ntr: ["Technology Business"],
    },
  },
  {
    stjCd: "AP064",
    lgnm: "EduConnect",
    stj: "Connecting Knowledge",
    dty: "Regular",
    cxdt: "",
    gstin: "56PQRST7120UVWX",
    einvoiceStatus: "Yes",
    nba: ["Education and Training"],
    lstupdt: "09/10/2023",
    rgdt: "02/15/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP065",
    ctj: "Educational Coordinator",
    tradeNam: "EduFusion",
    adadr: [
      {
        addr: {
          bnm: "Education Center",
          st: "20, Learning Street",
          loc: "Education District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90043",
        },
        ntr: ["Education and Training Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Learning Hub",
        st: "25, Knowledge Avenue",
        loc: "Intellectville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90044",
      },
      ntr: ["Education and Training Business"],
    },
  },
  {
    stjCd: "AP061",
    lgnm: "NourishWell Foods",
    stj: "Nourishing Every Bite",
    dty: "Regular",
    cxdt: "",
    gstin: "56PQRST3390UVWX",
    einvoiceStatus: "Yes",
    nba: ["Food and Beverage"],
    lstupdt: "12/08/2023",
    rgdt: "05/20/2018",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP062",
    ctj: "Food Scientist",
    tradeNam: "NourishFusion",
    adadr: [
      {
        addr: {
          bnm: "Nourish Factory",
          st: "30, Nutrition Street",
          loc: "Food District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10045",
        },
        ntr: ["Food and Beverage Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Food Hub",
        st: "15, Gourmet Avenue",
        loc: "Culinaryville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10046",
      },
      ntr: ["Food and Beverage Business"],
    },
  },
  {
    stjCd: "AP062",
    lgnm: "InnovateMind Solutions",
    stj: "Empowering Minds",
    dty: "Regular",
    cxdt: "",
    gstin: "12YZAB0078CDEFG",
    einvoiceStatus: "Yes",
    nba: ["Education and Training"],
    lstupdt: "11/05/2023",
    rgdt: "04/12/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP063",
    ctj: "Educator",
    tradeNam: "MindInnovate",
    adadr: [
      {
        addr: {
          bnm: "Education Center",
          st: "20, Learning Street",
          loc: "Education District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90047",
        },
        ntr: ["Education and Training Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Learning Hub",
        st: "25, Knowledge Avenue",
        loc: "Intellectville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90048",
      },
      ntr: ["Education and Training Business"],
    },
  },
  {
    stjCd: "AP059",
    lgnm: "HealthHub Clinic",
    stj: "Your Health, Our Priority",
    dty: "Regular",
    cxdt: "",
    gstin: "12YZAB5677CDEFG",
    einvoiceStatus: "Yes",
    nba: ["Healthcare Services"],
    lstupdt: "02/05/2023",
    rgdt: "07/12/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP060",
    ctj: "Medical Director",
    tradeNam: "WellnessHub",
    adadr: [
      {
        addr: {
          bnm: "Wellness Center",
          st: "30, Health Street",
          loc: "Health District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10043",
        },
        ntr: ["Healthcare Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Health Hub",
        st: "15, Wellness Avenue",
        loc: "Wellnessville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10044",
      },
      ntr: ["Healthcare Business"],
    },
  },
  {
    stjCd: "AP060",
    lgnm: "TechNexus Solutions",
    stj: "Connecting Innovations",
    dty: "Regular",
    cxdt: "",
    gstin: "90HIJK0034LMNOP",
    einvoiceStatus: "Yes",
    nba: ["Technology Services"],
    lstupdt: "01/15/2023",
    rgdt: "06/28/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP061",
    ctj: "Tech Expert",
    tradeNam: "TechNexus",
    adadr: [
      {
        addr: {
          bnm: "Tech Center",
          st: "20, Tech Street",
          loc: "Innovation District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90043",
        },
        ntr: ["Technology Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Innovation Hub",
        st: "25, Innovation Avenue",
        loc: "Techville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90044",
      },
      ntr: ["Technology Business"],
    },
  },
  {
    stjCd: "AP057",
    lgnm: "GreenSolutions",
    stj: "Sustainable Innovations",
    dty: "Regular",
    cxdt: "",
    gstin: "12LMNO5678PQRST",
    einvoiceStatus: "Yes",
    nba: ["Environmental Services"],
    lstupdt: "04/12/2023",
    rgdt: "09/10/2018",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP058",
    ctj: "Environmental Consultant",
    tradeNam: "EcoInnovations",
    adadr: [
      {
        addr: {
          bnm: "Eco Center",
          st: "30, Green Street",
          loc: "Eco District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10045",
        },
        ntr: ["Environmental Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Innovate Hub",
        st: "15, Innovation Avenue",
        loc: "Innovationville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10046",
      },
      ntr: ["Environmental Business"],
    },
  },
  {
    stjCd: "AP058",
    lgnm: "AdventureSeekers",
    stj: "Explore Your Limits",
    dty: "Regular",
    cxdt: "",
    gstin: "56PQRST4590UVWX",
    einvoiceStatus: "Yes",
    nba: ["Travel and Tourism"],
    lstupdt: "03/18/2023",
    rgdt: "08/20/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP059",
    ctj: "Adventure Guide",
    tradeNam: "AdventureFusion",
    adadr: [
      {
        addr: {
          bnm: "Adventure Center",
          st: "20, Adventure Street",
          loc: "Exploration District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90047",
        },
        ntr: ["Travel and Tourism Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Explore Hub",
        st: "25, Exploration Avenue",
        loc: "Discoveryville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90048",
      },
      ntr: ["Travel and Tourism Business"],
    },
  },
  {
    stjCd: "AP055",
    lgnm: "HealthyBites",
    stj: "Nourish Your Body",
    dty: "Regular",
    cxdt: "",
    gstin: "56PQRST6790UVWX",
    einvoiceStatus: "Yes",
    nba: ["Health and Wellness"],
    lstupdt: "06/10/2023",
    rgdt: "11/22/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP056",
    ctj: "Nutritionist",
    tradeNam: "NutriFusion",
    adadr: [
      {
        addr: {
          bnm: "Nutrition Center",
          st: "30, Wellness Street",
          loc: "Health District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10043",
        },
        ntr: ["Health and Wellness Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Nutrition Hub",
        st: "15, Nourish Avenue",
        loc: "Wellnessville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10044",
      },
      ntr: ["Health and Wellness Business"],
    },
  },
  {
    stjCd: "AP056",
    lgnm: "ArtisticExpressions",
    stj: "Unleash Creativity",
    dty: "Regular",
    cxdt: "",
    gstin: "80HIJK1234LMNOP",
    einvoiceStatus: "Yes",
    nba: ["Art and Craft"],
    lstupdt: "05/15/2023",
    rgdt: "10/28/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP057",
    ctj: "Art Instructor",
    tradeNam: "ArtFusion",
    adadr: [
      {
        addr: {
          bnm: "Art Studio",
          st: "20, Art Street",
          loc: "Creative District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90043",
        },
        ntr: ["Artistic Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Inspire Hub",
        st: "25, Inspiration Avenue",
        loc: "Imaginationville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90044",
      },
      ntr: ["Artistic Business"],
    },
  },
  {
    stjCd: "AP053",
    lgnm: "GreenBites Cafe",
    stj: "Sustainable Dining",
    dty: "Regular",
    cxdt: "",
    gstin: "90UVWX1234YZABCD",
    einvoiceStatus: "Yes",
    nba: ["Food and Beverage"],
    lstupdt: "08/12/2023",
    rgdt: "01/20/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP054",
    ctj: "Cafe Owner",
    tradeNam: "EcoCuisine",
    adadr: [
      {
        addr: {
          bnm: "Eco Cafe",
          st: "30, Green Street",
          loc: "Culinary District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10045",
        },
        ntr: ["Food and Beverage Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Culinary Hub",
        st: "15, Gourmet Avenue",
        loc: "Flavorville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10046",
      },
      ntr: ["Food and Beverage Business"],
    },
  },
  {
    stjCd: "AP054",
    lgnm: "InnovateTech Solutions",
    stj: "Innovate with Technology",
    dty: "Regular",
    cxdt: "",
    gstin: "12YZAB0000CDEFG",
    einvoiceStatus: "Yes",
    nba: ["Technology Services"],
    lstupdt: "07/15/2023",
    rgdt: "12/05/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP055",
    ctj: "Tech Innovator",
    tradeNam: "TechInnovate",
    adadr: [
      {
        addr: {
          bnm: "Innovate Center",
          st: "20, Tech Street",
          loc: "Innovation District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90047",
        },
        ntr: ["Technology Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Inno Hub",
        st: "25, Innovation Avenue",
        loc: "Techville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90048",
      },
      ntr: ["Technology Business"],
    },
  },
  {
    stjCd: "AP051",
    lgnm: "MindfulMinds Wellness Center",
    stj: "Nurture Your Mind",
    dty: "Regular",
    cxdt: "",
    gstin: "12LMNO5678PQRST",
    einvoiceStatus: "Yes",
    nba: ["Wellness Services"],
    lstupdt: "10/18/2023",
    rgdt: "03/22/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP052",
    ctj: "Wellness Therapist",
    tradeNam: "MindfulnessFusion",
    adadr: [
      {
        addr: {
          bnm: "Mindfulness Center",
          st: "30, Wellness Street",
          loc: "Mindfulness District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10043",
        },
        ntr: ["Wellness Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Mindfulness Hub",
        st: "15, Mind Avenue",
        loc: "Mindville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10044",
      },
      ntr: ["Wellness Business"],
    },
  },
  {
    stjCd: "AP052",
    lgnm: "EventElegance",
    stj: "Create Memorable Moments",
    dty: "Regular",
    cxdt: "",
    gstin: "56PQRST0100UVWX",
    einvoiceStatus: "Yes",
    nba: ["Event Planning"],
    lstupdt: "09/10/2023",
    rgdt: "02/15/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP053",
    ctj: "Event Coordinator",
    tradeNam: "EventFusion",
    adadr: [
      {
        addr: {
          bnm: "Event Center",
          st: "20, Event Street",
          loc: "Celebration District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90049",
        },
        ntr: ["Event Planning Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Celebrate Hub",
        st: "25, Moment Avenue",
        loc: "Memoraville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90050",
      },
      ntr: ["Event Planning Business"],
    },
  },
  {
    stjCd: "AP049",
    lgnm: "GreenHarvest Farms",
    stj: "Organic Cultivation",
    dty: "Regular",
    cxdt: "",
    gstin: "56CDEFG7890HIJKL",
    einvoiceStatus: "Yes",
    nba: ["Agriculture Services"],
    lstupdt: "12/08/2023",
    rgdt: "05/20/2018",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP050",
    ctj: "Agricultural Specialist",
    tradeNam: "EcoGrow",
    adadr: [
      {
        addr: {
          bnm: "Eco Farm",
          st: "30, Green Street",
          loc: "Farmers District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10041",
        },
        ntr: ["Agricultural Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Grow Hub",
        st: "15, Harvest Avenue",
        loc: "Cultivationville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10042",
      },
      ntr: ["Agricultural Business"],
    },
  },
  {
    stjCd: "AP050",
    lgnm: "CodeCrafters",
    stj: "Build Your Vision",
    dty: "Regular",
    cxdt: "",
    gstin: "90HIJK1904LMNOP",
    einvoiceStatus: "Yes",
    nba: ["Software Development"],
    lstupdt: "11/05/2023",
    rgdt: "04/12/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP051",
    ctj: "Tech Enthusiast",
    tradeNam: "TechCraft",
    adadr: [
      {
        addr: {
          bnm: "Tech Center",
          st: "20, Tech Street",
          loc: "Innovation District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90047",
        },
        ntr: ["Technology Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Inno Hub",
        st: "25, Innovation Avenue",
        loc: "Techville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90048",
      },
      ntr: ["Technology Business"],
    },
  },
  {
    stjCd: "AP047",
    lgnm: "Nature'sGift Store",
    stj: "Bringing Nature Home",
    dty: "Regular",
    cxdt: "",
    gstin: "90UVWX1234YZABCD",
    einvoiceStatus: "Yes",
    nba: ["Retail Services"],
    lstupdt: "02/05/2023",
    rgdt: "07/12/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP048",
    ctj: "Store Manager",
    tradeNam: "EcoHaven",
    adadr: [
      {
        addr: {
          bnm: "Eco Store",
          st: "30, Nature Street",
          loc: "Eco District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10039",
        },
        ntr: ["Retail Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Nature Hub",
        st: "15, Green Avenue",
        loc: "Natureville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10040",
      },
      ntr: ["Retail Business"],
    },
  },
  {
    stjCd: "AP048",
    lgnm: "CraftyCreations",
    stj: "Unleash Your Creativity",
    dty: "Regular",
    cxdt: "",
    gstin: "12YZAB4478CDEFG",
    einvoiceStatus: "Yes",
    nba: ["Art and Craft"],
    lstupdt: "01/15/2023",
    rgdt: "06/28/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP049",
    ctj: "Creative Director",
    tradeNam: "CraftFusion",
    adadr: [
      {
        addr: {
          bnm: "Craft Center",
          st: "20, Art Street",
          loc: "Creative District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90045",
        },
        ntr: ["Artistic Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Creation Hub",
        st: "25, Craft Avenue",
        loc: "Artville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90046",
      },
      ntr: ["Artistic Business"],
    },
  },
  {
    stjCd: "AP045",
    lgnm: "Healthwise Clinic",
    stj: "Your Wellness Partner",
    dty: "Regular",
    cxdt: "",
    gstin: "56LMNO7890PQRS",
    einvoiceStatus: "Yes",
    nba: ["Healthcare Services"],
    lstupdt: "04/12/2023",
    rgdt: "09/10/2018",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP046",
    ctj: "Medical Director",
    tradeNam: "WellnessFirst",
    adadr: [
      {
        addr: {
          bnm: "Wellness Center",
          st: "30, Health Street",
          loc: "Health District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10037",
        },
        ntr: ["Healthcare Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Health Hub",
        st: "15, Wellness Avenue",
        loc: "Wellnessville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10038",
      },
      ntr: ["Healthcare Business"],
    },
  },
  {
    stjCd: "AP046",
    lgnm: "TechSavvy Solutions",
    stj: "Digital Innovations",
    dty: "Regular",
    cxdt: "",
    gstin: "78PQRST9012UVWX",
    einvoiceStatus: "Yes",
    nba: ["Technology Services"],
    lstupdt: "03/08/2023",
    rgdt: "08/18/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP047",
    ctj: "Tech Guru",
    tradeNam: "TechFusion",
    adadr: [
      {
        addr: {
          bnm: "Tech Center",
          st: "20, Tech Street",
          loc: "Innovation District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90043",
        },
        ntr: ["Technology Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Inno Hub",
        st: "25, Innovation Avenue",
        loc: "Techville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90044",
      },
      ntr: ["Technology Business"],
    },
  },
  {
    stjCd: "AP043",
    lgnm: "GreenSolutions",
    stj: "Environmental Innovations",
    dty: "Regular",
    cxdt: "",
    gstin: "90CDEFG1234HIJK",
    einvoiceStatus: "Yes",
    nba: ["Environmental Services"],
    lstupdt: "06/10/2023",
    rgdt: "11/22/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP044",
    ctj: "Environmental Consultant",
    tradeNam: "EcoSolutions",
    adadr: [
      {
        addr: {
          bnm: "Eco Center",
          st: "30, Green Street",
          loc: "Sustainability District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10035",
        },
        ntr: ["Environmental Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Eco Hub",
        st: "15, Eco Avenue",
        loc: "GreenVille",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10036",
      },
      ntr: ["Environmental Business"],
    },
  },
  {
    stjCd: "AP044",
    lgnm: "TravelEra Expeditions",
    stj: "Journey Beyond",
    dty: "Regular",
    cxdt: "",
    gstin: "12HIJK5678LMNO",
    einvoiceStatus: "Yes",
    nba: ["Travel and Tourism"],
    lstupdt: "05/18/2023",
    rgdt: "10/28/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP045",
    ctj: "Travel Guide",
    tradeNam: "EraJourneys",
    adadr: [
      {
        addr: {
          bnm: "Journey Center",
          st: "20, Travel Street",
          loc: "Adventurer's District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90041",
        },
        ntr: ["Travel and Tourism Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Adventure Hub",
        st: "25, Explore Avenue",
        loc: "Discoveryville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90042",
      },
      ntr: ["Travel and Tourism Business"],
    },
  },
  {
    stjCd: "AP041",
    lgnm: "FitFusion Studios",
    stj: "Empower Your Fitness",
    dty: "Regular",
    cxdt: "",
    gstin: "34UVWX5678YZAB",
    einvoiceStatus: "Yes",
    nba: ["Fitness Services"],
    lstupdt: "08/18/2023",
    rgdt: "01/22/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP042",
    ctj: "Fitness Trainer",
    tradeNam: "FusionFit",
    adadr: [
      {
        addr: {
          bnm: "Fitness Center",
          st: "30, Fitness Street",
          loc: "Empowerment District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10033",
        },
        ntr: ["Fitness Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Empower Hub",
        st: "15, Strength Avenue",
        loc: "Fitnessville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10034",
      },
      ntr: ["Fitness Business"],
    },
  },
  {
    stjCd: "AP042",
    lgnm: "Dreamscape Studios",
    stj: "Unleash Creativity",
    dty: "Regular",
    cxdt: "",
    gstin: "56YZAB7890CDEF",
    einvoiceStatus: "Yes",
    nba: ["Art and Design"],
    lstupdt: "07/15/2023",
    rgdt: "12/05/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP043",
    ctj: "Art Director",
    tradeNam: "ArtDreams",
    adadr: [
      {
        addr: {
          bnm: "Dreamscape Center",
          st: "20, Art Street",
          loc: "Imagination District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90039",
        },
        ntr: ["Artistic Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Imagination Hub",
        st: "25, Creativity Avenue",
        loc: "Dreamsville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90040",
      },
      ntr: ["Artistic Business"],
    },
  },
  {
    stjCd: "AP039",
    lgnm: "GreenTech Innovations",
    stj: "Sustainable Solutions",
    dty: "Regular",
    cxdt: "",
    gstin: "90MNOP1234QRST",
    einvoiceStatus: "Yes",
    nba: ["Environmental Services"],
    lstupdt: "10/05/2023",
    rgdt: "03/15/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP040",
    ctj: "Environmental Engineer",
    tradeNam: "EcoTech",
    adadr: [
      {
        addr: {
          bnm: "Eco Center",
          st: "30, Green Street",
          loc: "Sustainability District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10031",
        },
        ntr: ["Environmental Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Sustain Hub",
        st: "15, Eco Avenue",
        loc: "GreenVille",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10032",
      },
      ntr: ["Environmental Business"],
    },
  },
  {
    stjCd: "AP040",
    lgnm: "MediaVibes Productions",
    stj: "Capture Moments",
    dty: "Regular",
    cxdt: "",
    gstin: "12QRST5678UVWX",
    einvoiceStatus: "Yes",
    nba: ["Media Services"],
    lstupdt: "09/08/2023",
    rgdt: "02/20/2018",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP041",
    ctj: "Creative Director",
    tradeNam: "VibeMedia",
    adadr: [
      {
        addr: {
          bnm: "Media Center",
          st: "20, Media Street",
          loc: "Creative District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90037",
        },
        ntr: ["Media Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Vibe Hub",
        st: "25, Capture Avenue",
        loc: "Imaginaryville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90038",
      },
      ntr: ["Media Business"],
    },
  },
  {
    stjCd: "AP037",
    lgnm: "MindfulJourney",
    stj: "Inner Exploration",
    dty: "Regular",
    cxdt: "",
    gstin: "56EFGH7890IJKL",
    einvoiceStatus: "Yes",
    nba: ["Wellness Services"],
    lstupdt: "12/10/2023",
    rgdt: "05/25/2015",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP038",
    ctj: "Wellness Guide",
    tradeNam: "SoulFusion",
    adadr: [
      {
        addr: {
          bnm: "Wellness Haven",
          st: "30, Inner Street",
          loc: "Soul District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10029",
        },
        ntr: ["Wellness Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Soul Sanctuary",
        st: "15, Spirit Avenue",
        loc: "Soulville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10030",
      },
      ntr: ["Wellness Business"],
    },
  },
  {
    stjCd: "AP038",
    lgnm: "JoyfulRhythms Dance Studio",
    stj: "Move to the Beat",
    dty: "Regular",
    cxdt: "",
    gstin: "67IJKLM8901MNOP",
    einvoiceStatus: "Yes",
    nba: ["Dance and Fitness"],
    lstupdt: "11/18/2023",
    rgdt: "04/10/2018",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP039",
    ctj: "Dance Director",
    tradeNam: "GrooveFusion",
    adadr: [
      {
        addr: {
          bnm: "Dance Center",
          st: "20, Dance Street",
          loc: "Rhythm District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90035",
        },
        ntr: ["Dance and Fitness Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Groove Hub",
        st: "25, Beat Avenue",
        loc: "Moveville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90036",
      },
      ntr: ["Dance and Fitness Business"],
    },
  },
  {
    stjCd: "AP035",
    lgnm: "PetParadise",
    stj: "Pet Care Haven",
    dty: "Regular",
    cxdt: "",
    gstin: "12WXYZ3456ABCD",
    einvoiceStatus: "Yes",
    nba: ["Pet Services"],
    lstupdt: "02/18/2023",
    rgdt: "07/22/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP036",
    ctj: "Pet Care Specialist",
    tradeNam: "PawFusion",
    adadr: [
      {
        addr: {
          bnm: "Pet Haven",
          st: "30, Pet Care Street",
          loc: "Animal District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10027",
        },
        ntr: ["Pet Care Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Pet Palace",
        st: "15, Pet Avenue",
        loc: "Petville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10028",
      },
      ntr: ["Pet Care Business"],
    },
  },
  {
    stjCd: "AP036",
    lgnm: "HealthyBites",
    stj: "Nutrition Delights",
    dty: "Regular",
    cxdt: "",
    gstin: "34ABCD5678EFGH",
    einvoiceStatus: "Yes",
    nba: ["Nutrition Services"],
    lstupdt: "01/28/2023",
    rgdt: "06/18/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP037",
    ctj: "Nutritionist",
    tradeNam: "NutriFusion",
    adadr: [
      {
        addr: {
          bnm: "Nutrition Center",
          st: "20, Nutrition Street",
          loc: "Health District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90033",
        },
        ntr: ["Nutrition Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Healthy Hub",
        st: "25, Wellness Avenue",
        loc: "Vitalityville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90034",
      },
      ntr: ["Nutrition Business"],
    },
  },
  {
    stjCd: "AP033",
    lgnm: "GreenScape Gardens",
    stj: "Nature's Paradise",
    dty: "Regular",
    cxdt: "",
    gstin: "78NPQR9012STUV",
    einvoiceStatus: "Yes",
    nba: ["Landscaping Services"],
    lstupdt: "04/15/2023",
    rgdt: "08/30/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP034",
    ctj: "Landscape Designer",
    tradeNam: "EcoScape",
    adadr: [
      {
        addr: {
          bnm: "Nature Haven",
          st: "30, Green Street",
          loc: "Eco District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10025",
        },
        ntr: ["Landscaping Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Eco Hub",
        st: "15, Nature Avenue",
        loc: "Greenville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10026",
      },
      ntr: ["Landscaping Business"],
    },
  },
  {
    stjCd: "AP034",
    lgnm: "UrbanBites Food Truck",
    stj: "Street Eats",
    dty: "Regular",
    cxdt: "",
    gstin: "90STUV1234WXYZ",
    einvoiceStatus: "Yes",
    nba: ["Street Food"],
    lstupdt: "03/12/2023",
    rgdt: "09/28/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP035",
    ctj: "Foodiepreneur",
    tradeNam: "FoodFusion Truck",
    adadr: [
      {
        addr: {
          bnm: "Foodie Zone",
          st: "20, Street Food Street",
          loc: "Foodie District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90031",
        },
        ntr: ["Street Food Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Foodie Hub",
        st: "25, Taste Avenue",
        loc: "Flavorville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90032",
      },
      ntr: ["Street Food Business"],
    },
  },
  {
    stjCd: "AP031",
    lgnm: "BrightFutures Academy",
    stj: "Educate to Elevate",
    dty: "Regular",
    cxdt: "",
    gstin: "56FGHI7890JKLM",
    einvoiceStatus: "Yes",
    nba: ["Education Services"],
    lstupdt: "06/10/2023",
    rgdt: "09/22/2015",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP032",
    ctj: "Principal",
    tradeNam: "EduVista",
    adadr: [
      {
        addr: {
          bnm: "Education Center",
          st: "30, Education Street",
          loc: "Knowledge District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10023",
        },
        ntr: ["Education Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Learning Hub",
        st: "15, Knowledge Avenue",
        loc: "Learnville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10024",
      },
      ntr: ["Education Business"],
    },
  },
  {
    stjCd: "AP032",
    lgnm: "TechNest Solutions",
    stj: "Innovate Tomorrow",
    dty: "Regular",
    cxdt: "",
    gstin: "67JKLM8901NPQR",
    einvoiceStatus: "Yes",
    nba: ["Technology Services"],
    lstupdt: "05/28/2023",
    rgdt: "07/18/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP033",
    ctj: "Tech Director",
    tradeNam: "InnoTechNest",
    adadr: [
      {
        addr: {
          bnm: "Innovation Center",
          st: "20, Tech Street",
          loc: "Innovation District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90029",
        },
        ntr: ["Technology Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "TechHub Place",
        st: "25, Innovation Avenue",
        loc: "Techville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90030",
      },
      ntr: ["Technology Business"],
    },
  },
  {
    stjCd: "AP029",
    lgnm: "CulinaryElegance",
    stj: "Gourmet Delights",
    dty: "Regular",
    cxdt: "",
    gstin: "12XYZA3456BCDE",
    einvoiceStatus: "Yes",
    nba: ["Culinary Services"],
    lstupdt: "08/20/2023",
    rgdt: "06/05/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP030",
    ctj: "Chef",
    tradeNam: "FoodFusion",
    adadr: [
      {
        addr: {
          bnm: "Culinary Haven",
          st: "30, Gourmet Street",
          loc: "Cuisine District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10021",
        },
        ntr: ["Culinary Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Taste Center",
        st: "15, Flavor Avenue",
        loc: "Tasteville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10022",
      },
      ntr: ["Culinary Business"],
    },
  },
  {
    stjCd: "AP030",
    lgnm: "ArtisticExpressions",
    stj: "Creative Visions",
    dty: "Regular",
    cxdt: "",
    gstin: "34BCDE5678FGHI",
    einvoiceStatus: "Yes",
    nba: ["Art and Design"],
    lstupdt: "07/15/2023",
    rgdt: "03/28/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP031",
    ctj: "Art Director",
    tradeNam: "ArtVisions",
    adadr: [
      {
        addr: {
          bnm: "Art Studio",
          st: "20, Creative Street",
          loc: "Art District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90027",
        },
        ntr: ["Artistic Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Gallery House",
        st: "25, Vision Avenue",
        loc: "Artville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90028",
      },
      ntr: ["Artistic Business"],
    },
  },
  {
    stjCd: "AP027",
    lgnm: "HealthHub Wellness",
    stj: "Holistic Living",
    dty: "Regular",
    cxdt: "",
    gstin: "78PQRS2345TUVW",
    einvoiceStatus: "Yes",
    nba: ["Wellness Services"],
    lstupdt: "10/25/2023",
    rgdt: "09/10/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP028",
    ctj: "Wellness Director",
    tradeNam: "WellnessHub",
    adadr: [
      {
        addr: {
          bnm: "Wellness Center",
          st: "30, Wellness Street",
          loc: "Holistic District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10019",
        },
        ntr: ["Wellness Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Holistic Place",
        st: "15, Healing Avenue",
        loc: "Wellville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10020",
      },
      ntr: ["Wellness Business"],
    },
  },
  {
    stjCd: "AP028",
    lgnm: "ExploreMore Adventures",
    stj: "Discover the World",
    dty: "Regular",
    cxdt: "",
    gstin: "90TUVW3456XYZA",
    einvoiceStatus: "Yes",
    nba: ["Adventure Travel"],
    lstupdt: "09/18/2023",
    rgdt: "04/28/2018",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP029",
    ctj: "Adventure Director",
    tradeNam: "Adventura",
    adadr: [
      {
        addr: {
          bnm: "Adventure Center",
          st: "20, Adventure Street",
          loc: "Discovery District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90025",
        },
        ntr: ["Adventure Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Wanderlust Hub",
        st: "25, Explore Avenue",
        loc: "Journeyville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90026",
      },
      ntr: ["Adventure Business"],
    },
  },
  {
    stjCd: "AP025",
    lgnm: "Bookworm Haven",
    stj: "Literary Wonders",
    dty: "Regular",
    cxdt: "",
    gstin: "56GHIJ1234KLMN",
    einvoiceStatus: "Yes",
    nba: ["Publishing Services"],
    lstupdt: "12/15/2023",
    rgdt: "05/30/2015",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP026",
    ctj: "Editor-in-Chief",
    tradeNam: "NovelCraft",
    adadr: [
      {
        addr: {
          bnm: "Bookworm House",
          st: "30, Literary Street",
          loc: "Book District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10017",
        },
        ntr: ["Publishing Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Literary Haven",
        st: "15, Story Avenue",
        loc: "Bookville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10018",
      },
      ntr: ["Publishing Business"],
    },
  },
  {
    stjCd: "AP026",
    lgnm: "CreativeCanvas Artistry",
    stj: "Art Expressions",
    dty: "Regular",
    cxdt: "",
    gstin: "67KLMN1234PQRS",
    einvoiceStatus: "Yes",
    nba: ["Art and Design"],
    lstupdt: "11/02/2023",
    rgdt: "08/18/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP027",
    ctj: "Art Director",
    tradeNam: "CanvasCraft",
    adadr: [
      {
        addr: {
          bnm: "Art Haven",
          st: "20, Art Street",
          loc: "Gallery District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90023",
        },
        ntr: ["Artistic Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Gallery House",
        st: "25, Creation Avenue",
        loc: "Artville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90024",
      },
      ntr: ["Artistic Business"],
    },
  },
  {
    stjCd: "AP023",
    lgnm: "TechGenius Innovations",
    stj: "Tech Solutions",
    dty: "Regular",
    cxdt: "",
    gstin: "12XYZA1234BCDE",
    einvoiceStatus: "Yes",
    nba: ["Technology Services"],
    lstupdt: "02/28/2023",
    rgdt: "09/15/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP024",
    ctj: "Tech Director",
    tradeNam: "InnoTechGenius",
    adadr: [
      {
        addr: {
          bnm: "Innovation Tower",
          st: "30, Tech Street",
          loc: "Innovate District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10015",
        },
        ntr: ["Technology Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "TechLab Center",
        st: "15, Innovation Avenue",
        loc: "Techville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10016",
      },
      ntr: ["Technology Business"],
    },
  },
  {
    stjCd: "AP024",
    lgnm: "FashionFusion Trends",
    stj: "Style Studios",
    dty: "Regular",
    cxdt: "",
    gstin: "34BCDEF5678GHIJ",
    einvoiceStatus: "Yes",
    nba: ["Fashion Retail"],
    lstupdt: "01/12/2023",
    rgdt: "06/28/2018",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP025",
    ctj: "Fashion Director",
    tradeNam: "StyleFusion Trends",
    adadr: [
      {
        addr: {
          bnm: "Fashion Hub",
          st: "20, Style Street",
          loc: "Fashion District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90021",
        },
        ntr: ["Fashion Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Trendy Mall",
        st: "25, Chic Avenue",
        loc: "Trendville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90022",
      },
      ntr: ["Fashion Business"],
    },
  },
  {
    stjCd: "AP021",
    lgnm: "AdventureZone Travel",
    stj: "Explore the World",
    dty: "Regular",
    cxdt: "",
    gstin: "45NPQR1234STUV",
    einvoiceStatus: "Yes",
    nba: ["Travel Services"],
    lstupdt: "04/20/2023",
    rgdt: "10/10/2015",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP022",
    ctj: "Travel Director",
    tradeNam: "TravelQuest",
    adadr: [
      {
        addr: {
          bnm: "Adventure Center",
          st: "30, Travel Street",
          loc: "Journey District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10013",
        },
        ntr: ["Travel Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Wanderlust Place",
        st: "15, Explore Avenue",
        loc: "Discoveryville",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10014",
      },
      ntr: ["Travel Business"],
    },
  },
  {
    stjCd: "AP022",
    lgnm: "HealthFit Clinics",
    stj: "Wellness Care",
    dty: "Regular",
    cxdt: "",
    gstin: "56STUV7890WXYZ",
    einvoiceStatus: "Yes",
    nba: ["Healthcare Services"],
    lstupdt: "03/15/2023",
    rgdt: "07/05/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP023",
    ctj: "Health Director",
    tradeNam: "WellCare",
    adadr: [
      {
        addr: {
          bnm: "Wellness Center",
          st: "20, Health Street",
          loc: "Care District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90019",
        },
        ntr: ["Health Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Holistic Place",
        st: "25, Wellness Avenue",
        loc: "Healville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90020",
      },
      ntr: ["Health Business"],
    },
  },
  {
    stjCd: "AP019",
    lgnm: "MusicMinds Productions",
    stj: "Melody Studios",
    dty: "Regular",
    cxdt: "",
    gstin: "12FGHI5678JKLM",
    einvoiceStatus: "Yes",
    nba: ["Music Production"],
    lstupdt: "06/30/2023",
    rgdt: "11/15/2016",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP020",
    ctj: "Music Producer",
    tradeNam: "SoundCraft",
    adadr: [
      {
        addr: {
          bnm: "Sound Haven",
          st: "30, Music Street",
          loc: "Harmony District",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10011",
        },
        ntr: ["Music Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Note Studios",
        st: "15, Melody Avenue",
        loc: "Noteville",
        bno: "20",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10012",
      },
      ntr: ["Music Business"],
    },
  },
  {
    stjCd: "AP020",
    lgnm: "CozyNest Interiors",
    stj: "Home Designs",
    dty: "Regular",
    cxdt: "",
    gstin: "34JKLM7890NPQR",
    einvoiceStatus: "Yes",
    nba: ["Interior Design"],
    lstupdt: "05/12/2023",
    rgdt: "08/25/2019",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP021",
    ctj: "Design Director",
    tradeNam: "HomeHaven",
    adadr: [
      {
        addr: {
          bnm: "Design Hub",
          st: "20, Interior Street",
          loc: "Design District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90017",
        },
        ntr: ["Design Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Comfort Place",
        st: "25, Cozy Avenue",
        loc: "Relaxville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90018",
      },
      ntr: ["Design Business"],
    },
  },
  {
    stjCd: "AP017",
    lgnm: "SweetDelights Bakery",
    stj: "Bake and Enjoy",
    dty: "Regular",
    cxdt: "",
    gstin: "89YZAB2345CDEF",
    einvoiceStatus: "Yes",
    nba: ["Bakery"],
    lstupdt: "12/05/2023",
    rgdt: "03/12/2018",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP018",
    ctj: "Bakery Owner",
    tradeNam: "SweetTreats",
    adadr: [
      {
        addr: {
          bnm: "Taste Haven",
          st: "25, Bakery Street",
          loc: "Cakeland",
          bno: "5",
          stcd: "New York",
          flno: "2nd Floor",
          lt: "40.7128",
          lg: "-74.0060",
          pncd: "10009",
        },
        ntr: ["Bakery Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Cake Delight",
        st: "15, Dessert Avenue",
        loc: "Confectionery District",
        bno: "10",
        stcd: "New York",
        flno: "3rd Floor",
        lt: "40.7128",
        lg: "-74.0060",
        pncd: "10010",
      },
      ntr: ["Bakery Business"],
    },
  },
  {
    stjCd: "AP018",
    lgnm: "FashionFusion Boutique",
    stj: "Style Haven",
    dty: "Regular",
    cxdt: "",
    gstin: "90CDE3456FGHI",
    einvoiceStatus: "Yes",
    nba: ["Fashion Retail"],
    lstupdt: "09/28/2023",
    rgdt: "06/08/2017",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP019",
    ctj: "Fashion Director",
    tradeNam: "StyleFusion",
    adadr: [
      {
        addr: {
          bnm: "Fashion Center",
          st: "20, Style Street",
          loc: "Fashion District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90015",
        },
        ntr: ["Fashion Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Trendy Mall",
        st: "25, Chic Avenue",
        loc: "Trendville",
        bno: "15",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90016",
      },
      ntr: ["Fashion Business"],
    },
  },
  {
    stjCd: "AP015",
    lgnm: "GreenThumb Nursery",
    stj: "Plant Paradise",
    dty: "Regular",
    cxdt: "",
    gstin: "56PQRS6789TUVA",
    einvoiceStatus: "Yes",
    nba: ["Plant Retail"],
    lstupdt: "11/18/2023",
    rgdt: "05/02/2013",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP016",
    ctj: "Plant Enthusiast",
    tradeNam: "NatureGarden",
    adadr: [
      {
        addr: {
          bnm: "Nature's Haven",
          st: "30, Garden Lane",
          loc: "Greenland",
          bno: "5",
          stcd: "California",
          flno: "2nd Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90011",
        },
        ntr: ["Plant Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "Botanical Oasis",
        st: "10, Floral Avenue",
        loc: "Blossom District",
        bno: "15",
        stcd: "California",
        flno: "3rd Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90012",
      },
      ntr: ["Plant Business"],
    },
  },
  {
    stjCd: "AP016",
    lgnm: "TechVision Solutions",
    stj: "Innovate Tomorrow",
    dty: "Regular",
    cxdt: "",
    gstin: "78UVWX1234YZAB",
    einvoiceStatus: "Yes",
    nba: ["Technology Consulting"],
    lstupdt: "07/01/2023",
    rgdt: "09/20/2015",
    ctb: "Private Limited",
    sts: "Active",
    ctjCd: "AP017",
    ctj: "Technology Director",
    tradeNam: "InnoTechVision",
    adadr: [
      {
        addr: {
          bnm: "Innovation Center",
          st: "20, Technology Street",
          loc: "Innovation District",
          bno: "10",
          stcd: "California",
          flno: "4th Floor",
          lt: "37.7749",
          lg: "-122.4194",
          pncd: "90013",
        },
        ntr: ["Technology Business"],
      },
    ],
    pradr: {
      addr: {
        bnm: "InnoTech Hub",
        st: "15, Innovation Avenue",
        loc: "Techville",
        bno: "25",
        stcd: "California",
        flno: "5th Floor",
        lt: "37.7749",
        lg: "-122.4194",
        pncd: "90014",
      },
      ntr: ["Technology Business"],
    },
  },
];

export default data;
